main:
  linkcharac_path: "/Users/akuncheria/Documents/GSR-2021Feb/UCBerkeley_GSR/SAEF/Working_Files/Reclassification_STRF/final/may2022/bayarea_links_reclassification_noattr.csv"
  network_path : "/Users/akuncheria/Documents/GSR-2021Feb/UCBerkeley_GSR/Networks_Dataset/networks_dataset_Mobiliti/Nov2019/for_drive/July2021"
  links: "sf_links.csv"
  nodes: "sf_nodes.csv"

  sim_one_name: 'B60'
  sim_one_path: "/Users/akuncheria/Documents/GSR-2021Feb/UCBerkeley_GSR/Results_Mobiliti/2022-05-11 - RSR Bridge Closure (more scenarios)/2022-05-11-sf_rsr_baseline_060_noscen_links"
  sim_two_name: 'UET'
  sim_two_path: "/Users/akuncheria/Documents/GSR-2021Feb/UCBerkeley_GSR/Results_Mobiliti/2022-02-17 - SF Baseline, UET, SOT, SOF, 0% Rerouting/2022-02-17-sf_uet_000_links"
  sim_three_name: 'SOT'
  sim_three_path: "/Users/akuncheria/Documents/GSR-2021Feb/UCBerkeley_GSR/Results_Mobiliti/2022-02-17 - SF Baseline, UET, SOT, SOF, 0% Rerouting/2022-02-17-sf_sot_000_links"
  sim_four_name: 'SOF'
  sim_four_path: "/Users/akuncheria/Documents/GSR-2021Feb/UCBerkeley_GSR/Results_Mobiliti/2022-02-17 - SF Baseline, UET, SOT, SOF, 0% Rerouting/2022-02-17-sf_sof_000_links"
  fpath : "avg_flow_rates.tsv"
  spath : "avg_speeds.tsv"
  fupath : "fuel_consumption.tsv"
  truckcountpath: "purpose_counts.11.tsv"
  legs_one_path: ""
  legs_two_path: ""
  

  boundary_root: '/Users/akuncheria/Documents/GSR-2021Feb/UCBerkeley_GSR/SAEF/Working_Files/Cities/boundry_shapefiles'
  processed_path: '../data/processed_data'

  clippedlinks_dir: "/Users/akuncheria/Documents/GSR-2021Feb/UCBerkeley_GSR/SAEF - WIP/data/processed_data"

test:
  boundary_root:  '/Users/akuncheria/Documents/GSR-2021Feb/UCBerkeley_GSR/SAEF - WIP/data/boundary_shapefiles'
